### ISSUE TITLE
Clear SCCLMPT Button clears complete Wii U NAND.

### ISSUE THREAD

**Issue by Vadenimo** [GaryOderNichts/vWii-NAND-Restorer#1]
Hi, i'm Mario_TV.
I found an Issue after pressing the Clear SLCCMPT Button, it clears everything from the Wii U System Menu Files. That's then a Brick, with the 101 Error Code. It would be great, for fixing it.

**Comment by GaryOderNichts** [comment]
No it won't clear the whole Wii U NAND.
This Error occurs when you return to the Home Menu without restoring your SLCCMPT.
Try removing the Disc, unplugging all HDDs and then power it back on.

**Comment by Vadenimo** [comment]
Okay, thanks it works now!
